'use strict';
const $=id=>document.getElementById(id), fmt=(n,d=2)=>n==null?'—':n.toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d}), euro=n=>fmt(n)+' €';
const date=t=>new Date(t*1000).toLocaleString('fr-FR',{timeZone:'Europe/Paris',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let current=null, charts=[],editId=null,pendingId=null,revision=0;
$('month').value=today.slice(0,7);$('month').max=today.slice(0,7);$('fuel-date').value=today;$('fuel-date').max=today;
const setStatus=s=>$('status').textContent=s;
async function api(path,method='GET',body){const r=await fetch('/mobility-api'+path,{method,headers:{...(body?{'Content-Type':'application/json','X-Mobility-Request':'1'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(120000)});const data=await r.json();if(!r.ok){throw Error(data.error||'Erreur de connexion');}return data;}
function td(row,text){const cell=document.createElement('td');cell.textContent=text;row.append(cell);return cell;}
async function load(){const rev=++revision;setStatus('Chargement des mesures…');$('refresh').disabled=true;try{const d=await api('/summary?month='+$('month').value);if(rev!==revision)return;current=d;setStatus('');render(d);charts.forEach(c=>c.resize());}catch(e){if(rev===revision)setStatus(e.message);}finally{$('refresh').disabled=false;}}
function render(d){const totals=Object.values(d.totals),kwh=totals.reduce((s,t)=>s+t.kwh,0),cost=totals.reduce((s,t)=>s+t.cost,0),unpriced=totals.reduce((s,t)=>s+t.unpriced,0);$('energy').textContent=d.hasData===false?'—':fmt(kwh)+' kWh';$('electric-cost').textContent=d.hasData===false?'—':unpriced?'Incomplet':euro(cost);$('fuel-cost').textContent=euro(d.fuelCost);$('total-cost').textContent=d.hasData===false?'—':unpriced?'Incomplet':euro(cost+d.fuelCost);$('sessions-count').textContent=d.hasData===false?'Pas de mesures sur la période':d.sessions.length+' sessions détectées'+(d.missingIntervals?' · couverture partielle':'');$('unassigned').textContent=fmt(d.totals.unknown.kwh)+' kWh à attribuer';$('updated').textContent='Mesures actualisées à '+date(d.updatedAt);
 for(const v of ['bmw','mini']){const t=d.totals[v],box=$(v+'-summary');box.replaceChildren();const strong=document.createElement('strong');strong.textContent=fmt(t.kwh)+' kWh · '+(t.unpriced?'coût incomplet':euro(t.cost));box.append(strong);const p=document.createElement('p');p.className='muted';p.textContent=t.sessions+' sessions attribuées'+(v==='bmw'?' · '+euro(d.fuelCost)+' d’essence achetée':'');box.append(p);const ratio=document.createElement('p');ratio.className='muted';const km=v==='bmw'?d.bmwKm:d.miniKm;ratio.textContent=(d.odometers[v]!=null?'Compteur : '+fmt(d.odometers[v],0)+' km · ':'')+(km==null?'Historique insuffisant pour les kilomètres de la période':fmt(km,1)+' km sur la période'+(km>0&&!t.unpriced&&d.totals.unknown.kwh===0?' · '+euro((t.cost+(v==='bmw'?d.fuelCost:0))/km*100)+'/100 km (budget)':' · ratio en attente de kilomètres ou des attributions'));box.append(ratio);}
 $('quality').textContent='Contrôles : '+(d.missingIntervals||0)+' intervalle(s) sans index exploitable · '+d.resets+' remise(s) à zéro du cumul · '+fmt(d.excludedKwh)+' kWh exclus pour saut anormal · '+fmt(d.standbyKwh)+' kWh de veille hors sessions.'+(d.historicalTariffEstimated?' Tarif historique partiellement estimé.':'')+(unpriced?' Certaines recharges n’ont pas de tarif identifiable.':'');
 const rows=$('sessions');rows.replaceChildren();for(const s of [...d.sessions].reverse()){const row=document.createElement('tr');td(row,date(s.start)+(s.partial?' *':''));td(row,fmt((s.end-s.start)/3600,1)+' h');const cell=td(row,'');const select=document.createElement('select');select.setAttribute('aria-label','Véhicule pour la recharge du '+date(s.start));for(const [v,label]of Object.entries(d.vehicles)){const o=new Option(label,v);o.selected=s.vehicle===v;select.add(o);}select.onchange=async()=>{select.disabled=true;try{await api('/assignment','POST',{session:s.id,vehicle:select.value});await load();}catch(e){setStatus(e.message);select.value=s.vehicle;select.disabled=false;}};cell.append(select);td(row,fmt(s.kwh)+' kWh');td(row,fmt(s.peak,1)+' kW');td(row,euro(s.cost));rows.append(row);}if(!d.sessions.length){const r=document.createElement('tr');td(r,'Aucune recharge détectée sur cette période.').colSpan=6;rows.append(r);}
 const fuels=$('fuel-rows');fuels.replaceChildren();for(const f of d.fuel){const r=document.createElement('tr');td(r,f.date.split('-').reverse().join('/'));td(r,euro(f.cents/100));td(r,fmt(f.litres));td(r,f.litres?euro(f.cents/100/f.litres):'—');td(r,fmt(f.odometer,0));td(r,f.note);const actions=td(r,'');const edit=document.createElement('button');edit.textContent='Modifier';edit.onclick=()=>{editId=f.id;pendingId=null;$('fuel-date').value=f.date;$('fuel-amount').value=f.cents/100;$('fuel-litres').value=f.litres??'';$('fuel-odo').value=f.odometer??'';$('fuel-note').value=f.note;$('fuel-save').textContent='Enregistrer la modification';$('fuel-cancel').hidden=false;$('fuel-form').scrollIntoView({behavior:'smooth'});};const del=document.createElement('button');del.textContent='Supprimer';del.onclick=async()=>{if(!confirm('Supprimer le plein du '+f.date+' ('+euro(f.cents/100)+') ?'))return;del.disabled=true;try{await api('/fuel','DELETE',{id:f.id});await load();}catch(e){setStatus(e.message);del.disabled=false;}};actions.append(edit,del);fuels.append(r);}if(!d.fuel.length){const r=document.createElement('tr');td(r,'Aucun plein saisi pour ce mois.').colSpan=7;fuels.append(r);}
 charts.forEach(c=>c.destroy());charts=[];if(typeof Chart==='undefined'){setStatus('Graphiques indisponibles : bibliothèque non chargée. Les tableaux restent accessibles.');return;}
 const days=[];const end=d.month===today.slice(0,7)?+today.slice(8):new Date(+d.month.slice(0,4),+d.month.slice(5),0).getDate();for(let i=1;i<=end;i++)days.push(d.month+'-'+String(i).padStart(2,'0'));
 const energySets=[['bmw','#427de2'],['mini','#ec9c38'],['unknown','#9aabb3']].map(([v,color])=>({label:d.vehicles[v]+' · kWh',data:days.map(day=>d.days[day]?.[v]||0),backgroundColor:color,borderRadius:3,maxBarThickness:28,yAxisID:'y',stack:'energy',order:2}));
 const kmSets=[['bmw','#2454a1'],['mini','#ac5907']].map(([v,color])=>({type:'line',label:d.vehicles[v]+' · km',data:days.map(day=>d.dailyKm?.[day]?.[v]??null),borderColor:color,backgroundColor:color,pointRadius:3,pointHoverRadius:5,borderWidth:2,borderDash:v==='mini'?[5,3]:[],spanGaps:false,tension:0,yAxisID:'km',order:1}));
 charts.push(new Chart($('daily'),{type:'bar',data:{labels:days.map(x=>x.slice(8)),datasets:[...energySets,...kmSets]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>c.dataset.label+': '+fmt(c.parsed.y,c.dataset.yAxisID==='km'?1:2)+' '+(c.dataset.yAxisID==='km'?'km':'kWh')}}},scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,beginAtZero:true,position:'left',title:{display:true,text:'Recharge · kWh'}},km:{stacked:false,beginAtZero:true,position:'right',grid:{drawOnChartArea:false},title:{display:true,text:'Distance · km'}}}}}));
 charts.push(new Chart($('power'),{type:'line',data:{datasets:[{label:'Borne · kW',data:d.power.map(([t,v])=>({x:t*1000,y:v})),borderColor:'#087f8c',backgroundColor:'#087f8c20',fill:true,pointRadius:0,borderWidth:2,spanGaps:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{title:items=>date(items[0].parsed.x/1000)}}},scales:{x:{type:'linear',ticks:{maxTicksLimit:6,callback:t=>new Date(t).toLocaleTimeString('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit'})},grid:{display:false}},y:{beginAtZero:true,title:{display:true,text:'kW'}}}}}));
}
function clearForm(){$('fuel-form').reset();$('fuel-date').value=today;editId=null;pendingId=null;$('fuel-save').textContent='Enregistrer le plein';$('fuel-cancel').hidden=true;}
$('fuel-form').onsubmit=async e=>{e.preventDefault();$('fuel-save').disabled=true;pendingId=pendingId||crypto.randomUUID().replaceAll('-','');const id=editId||pendingId;try{await api('/fuel','POST',{id,date:$('fuel-date').value,cost:$('fuel-amount').value,litres:$('fuel-litres').value,odometer:$('fuel-odo').value,note:$('fuel-note').value});$('month').value=$('fuel-date').value.slice(0,7);clearForm();await load();}catch(e){setStatus(e.message);}finally{$('fuel-save').disabled=false;}};
$('fuel-cancel').onclick=clearForm;$('month').onchange=load;$('refresh').onclick=load;
$('export').onclick=async()=>{try{const data=await api('/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mobilite-saisies-'+today+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setStatus(e.message);}};
load();
